# Generated by Django 3.1 on 2020-10-24 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogr_ogr',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 25)),
        ),
    ]
