# Generated by Django 3.1 on 2020-10-24 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ogr', '0002_auto_20201025_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogr_ogr',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
