# Generated by Django 3.1 on 2020-10-03 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogr', '0002_auto_20201003_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogr_ogr',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 3)),
        ),
    ]
